services:
  api-db-todoapp:
    build:
      context: .
      dockerfile: ./laravel/dev/Dockerfile
      args:
        UID: 1000
        GID: 1000
        UNAME: dan-wyn
      
    image: api-db-todoapp:latest
    container_name: api-db-todoapp
    user: 1000:1000
    volumes:
      - ../.:/var/www/
    ports:
      - "8000:8000" # for php artisan serve
    tty: true
